interface IProducts {
  img: string;
  id: string;
  name: string;
  price: number;
  amount: number;
  year: number;
  manufacturer: string;
  color: [string, string];
  numberOfCameras: number;
  popular: boolean;
}

const products: Array<IProducts> = [
  {
    img: "./assets/phone/Xiaomi Redmi 9A.jpeg",
    name: "Xiaomi Redmi 9A",
    id: "Xiaomi-Redmi-9A",
    price: 7169,
    amount: 10,
    year: 2020,
    manufacturer: "xiaomi",
    color: ["голубой", "blue"],
    numberOfCameras: 1,
    popular: true,
  },
  {
    img: "./assets/phone/Xiaomi Redmi 10.jpeg",
    name: "Xiaomi Redmi 10",
    id: "Xiaomi-Redmi-10",
    price: 16980,
    amount: 8,
    year: 2022,
    manufacturer: "xiaomi",
    color: ["серый", "gray"],
    numberOfCameras: 3,
    popular: true,
  },
  {
    img: "./assets/phone/Xiaomi 12 blue.jpeg",
    name: "Xiaomi 12",
    id: "Xiaomi-12-blue",
    price: 69990,
    amount: 5,
    year: 2021,
    manufacturer: "xiaomi",
    color: ["голубой", "blue"],
    numberOfCameras: 1,
    popular: false,
  },
  {
    img: "./assets/phone/Xiaomi 12 purple.jpeg",
    name: "Xiaomi 12",
    id: "Xiaomi-12-purple",
    price: 69990,
    amount: 3,
    year: 2021,
    manufacturer: "xiaomi",
    color: ["фиолетовый", "purple"],
    numberOfCameras: 1,
    popular: false,
  },
  {
    img: "./assets/phone/Xiaomi Redmi Note 11 Pro.jpeg",
    name: "Xiaomi Redmi Note 11 Pro",
    id: "Xiaomi-Redmi-Note-11-Pro",
    price: 27495,
    amount: 9,
    year: 2022,
    manufacturer: "xiaomi",
    color: ["черный", "black"],
    numberOfCameras: 1,
    popular: true,
  },
  {
    img: "./assets/phone/Xiaomi Redmi Note 11 Pro white.jpeg",
    name: "Xiaomi Redmi Note 11 Pro",
    id: "Xiaomi-Redmi-Note-11-Pro-white",
    price: 27495,
    amount: 2,
    year: 2022,
    manufacturer: "xiaomi",
    color: ["белый", "white"],
    numberOfCameras: 1,
    popular: true,
  },

  {
    img: "./assets/phone/Samsung Galaxy A23.jpeg",
    name: "Samsung Galaxy A23",
    id: "Samsung-Galaxy-A23",
    price: 17880,
    amount: 10,
    year: 2018,
    manufacturer: "samsung",
    color: ["белый", "white"],
    numberOfCameras: 3,
    popular: false,
  },
  {
    img: "./assets/phone/Samsung Galaxy A33.jpeg",
    name: "Samsung Galaxy A33",
    id: "Samsung-Galaxy-A33",
    price: 24940,
    amount: 7,
    year: 2019,
    manufacturer: "samsung",
    color: ["черный", "black"],
    numberOfCameras: 3,
    popular: false,
  },
  {
    img: "./assets/phone/Samsung Galaxy A73.jpeg",
    name: "Samsung Galaxy A73",
    id: "Samsung-Galaxy-A73",
    price: 31460,
    amount: 4,
    year: 2017,
    manufacturer: "samsung",
    color: ["серый", "gray"],
    numberOfCameras: 3,
    popular: false,
  },
  {
    img: "./assets/phone/Samsung Galaxy A12.jpeg",
    name: "Samsung Galaxy A12",
    id: "Samsung-Galaxy-A12",
    price: 14390,
    amount: 8,
    year: 2019,
    manufacturer: "samsung",
    color: ["голубой", "blue"],
    numberOfCameras: 4,
    popular: false,
  },
  {
    img: "./assets/phone/Samsung Galaxy S20.jpeg",
    name: "Samsung Galaxy S20",
    id: "Samsung-Galaxy-S20",
    price: 52180,
    amount: 10,
    year: 2022,
    manufacturer: "samsung",
    color: ["фиолетовый", "purple"],
    numberOfCameras: 4,
    popular: true,
  },
  {
    img: "./assets/phone/Samsung Galaxy A52.jpeg",
    name: "Samsung Galaxy A52",
    id: "Samsung-Galaxy-A52",
    price: 27480,
    amount: 6,
    year: 2021,
    manufacturer: "samsung",
    color: ["фиолетовый", "purple"],
    numberOfCameras: 3,
    popular: false,
  },
];
export default products;
